language: rust
rust:
  - stable
script:
  - cargo build --verbose
  - bash tests/fasten_metrics.sh
  - bash tests/fasten_clean.sh
  - bash tests/fasten_straighten.sh
  - bash tests/fasten_kmer.sh
  - bash tests/fasten_combine.sh
  - bash tests/fasten_trim.sh
  - bash tests/fasten_validate.sh
  - bash tests/fasten_shuffle.sh
  - bash tests/fasten_randomize.sh
  - bash tests/fasten_sample.sh
  - bash tests/fasten_quality_filter.sh
  - bash tests/fasten_regex.sh
  - bash tests/fasten_replace.sh
  - bash tests/fasten_collapse.sh
